name: Regenerate help messages of CLI commands

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  update-help-messages:
    if: github.repository_owner == 'packit'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install missing distro dependencies
        run: sudo apt update && sudo apt-get install libkrb5-dev python3-rpm

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip3 install packitos

      - name: Regenerate help messages
        run: python3 files/generate_cli_help_messages.py

      - name: Create pull request if there are changes
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update help messages of CLI commands"
          title: "Update help messages of CLI commands"
          body: "Automatically regenerated help messages for CLI command docs."
          delete-branch: true
